error: fix Display of Wrapped errors
snafu 0.8 changed the default output format.

Fixes: b839b3c1eebc ("deps: update to snafu v0.8")
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>