error: map SafetyViolation to EXDEV
It would be nice if there was an EUNSAFE we could use, but alas there is
no such errno, so we will have to reuse the same errno that openat2()
uses when a walk ends up outside of the rootfs.

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>