gha: clear tool cache
In a future patch we will end up expanding the amount of logs we get
from "make test", which will make GitHub Actions unhappy:

  System.IO.IOException: No space left on device:
  '/home/runner/actions-runner/cached/_diag/Worker_20250710-090101-utc.log'

So we need to be more aggressive about cleaning up unused space...

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>