gha: clear unused packages for CI
Our cargo tests require a decent amount of space for all the profile
information, which has caused us to start getting the following error
during CI runs:

 > Error: No space left on device (os error 28) at path "/tmp/.tmptg1faV"
 > LLVM Profile Error: Failed to write file
 > "/home/runner/work/libpathrs/libpathrs/target/llvm-cov-target/libpathrs-2591742-9389327919420937493_2.profraw":
 > No space left on device

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>